# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporte_personal_mensual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAsistenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('bloque_orden', models.PositiveSmallIntegerField(default=1)),
                ('estado_dia', models.CharField(choices=[('ASISTIO', 'Asistio'), ('FALTA', 'Falta'), ('JUSTIFICADO', 'Justificado'), ('DESCANSO_MEDICO', 'Descanso medico'), ('DESCANSO', 'Descanso'), ('FERIADO', 'Feriado')], default='ASISTIO', max_length=20)),
                ('hora_entrada_programada', models.TimeField(blank=True, null=True)),
                ('hora_salida_programada', models.TimeField(blank=True, null=True)),
                ('hora_entrada_real', models.TimeField(blank=True, null=True)),
                ('hora_salida_real', models.TimeField(blank=True, null=True)),
                ('minutos_tardanza', models.PositiveIntegerField(default=0)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='reporte_personal_mensual.reportepersonalmensual')),
            ],
            options={
                'db_table': 'reportes_asistencia_diaria',
                'ordering': ['reporte', 'fecha', 'bloque_orden'],
                'constraints': [models.UniqueConstraint(fields=('reporte', 'fecha', 'bloque_orden'), name='uq_reporte_asistencia_fecha_bloque')],
            },
        ),
    ]
