# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boleta_mensual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESCUENTO', 'Descuento')], max_length=12)),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='boleta_mensual.boletamensual')),
            ],
            options={
                'db_table': 'boletas_conceptos',
                'ordering': ['boleta', 'tipo', 'concepto'],
            },
        ),
    ]
