# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModuloPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modulo', models.CharField(choices=[('ESCRITORIO', 'Escritorio'), ('EMPRESAS', 'Empresas'), ('SUCURSALES', 'Sucursales'), ('AREAS', 'Areas'), ('CARGOS', 'Cargos'), ('TIPO_TRABAJADOR', 'Tipo trabajador'), ('TIPO_SINDICATO', 'Tipo sindicato'), ('CATEGORIAS', 'Categorias'), ('TURNOS', 'Turnos'), ('DISPOSITIVOS', 'Dispositivos'), ('DESCARGAR_MARCAS', 'Descargar marcas'), ('PERSONAL', 'Personal'), ('BOLETA_MENSUAL', 'Boleta mensual'), ('RESUMEN_PLANILLA', 'Resumen planilla'), ('MARCACIONES', 'Marcaciones'), ('PROCESAR_ASISTENCIA', 'Procesar asistencia'), ('CONSULTAR_ASISTENCIA', 'Consultar asistencia'), ('JUSTIFICACIONES', 'Registrar justificacion'), ('AUTORIZAR_JUSTIFICACION', 'Autorizar justificacion'), ('DESCANSO_MEDICO', 'Descanso medico'), ('USUARIOS', 'Usuarios')], max_length=40)),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_crear', models.BooleanField(default=False)),
                ('puede_editar', models.BooleanField(default=False)),
                ('puede_eliminar', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_modulos_permisos',
                'ordering': ['user_id', 'modulo'],
                'constraints': [models.UniqueConstraint(fields=('user', 'modulo'), name='uq_usuario_modulo_permiso')],
            },
        ),
    ]
