# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportePersonalMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_dias_periodo', models.PositiveSmallIntegerField(default=0)),
                ('total_dias_laborados', models.PositiveSmallIntegerField(default=0)),
                ('total_dias_falta', models.PositiveSmallIntegerField(default=0)),
                ('total_dias_justificados', models.PositiveSmallIntegerField(default=0)),
                ('total_dias_descanso_medico', models.PositiveSmallIntegerField(default=0)),
                ('total_minutos_tardanza', models.PositiveIntegerField(default=0)),
                ('total_horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'Generado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=12)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes_personal/')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_mensuales', to='personal.personal')),
            ],
            options={
                'db_table': 'reportes_personal_mensual',
                'ordering': ['-anio', '-mes', 'personal_id'],
                'constraints': [models.UniqueConstraint(fields=('personal', 'anio', 'mes'), name='uq_reporte_personal_periodo'), models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='ck_reporte_mes_1_12')],
            },
        ),
    ]
