# Generated by Django 6.0.2 on 2026-02-27 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BoletaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada'), ('DESCARGADA', 'Descargada'), ('ANULADA', 'Anulada')], default='GENERADA', max_length=12)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/')),
            ],
            options={
                'db_table': 'boletas_mensuales',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cargos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('periodos_vacacionales', models.BooleanField(default=False)),
                ('dias_por_periodo', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('direccion_tipo', models.CharField(choices=[('IP', 'Direccion IP'), ('DOMINIO', 'Dominio')], default='IP', max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('comunicacion', models.CharField(default='TCP/IP', max_length=40)),
                ('puerto', models.PositiveIntegerField(default=4370)),
                ('uso', models.CharField(choices=[('ASISTENCIA', 'Control de Asistencia'), ('ACCESO', 'Control de Acceso')], default='ASISTENCIA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dispositivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('logo', models.FileField(blank=True, null=True, upload_to='empresas/logos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_sindicato',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_trabajador',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('GENERAL_PERSONALIZADO', 'General Personalizado'), ('DESCANSO', 'Descanso')], default='GENERAL', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuarios_agua',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='BoletaConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESCUENTO', 'Descuento')], max_length=12)),
                ('concepto', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='core.boletamensual')),
            ],
            options={
                'db_table': 'boletas_conceptos',
                'ordering': ['boleta', 'tipo', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='DescargaMarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuente', models.CharField(choices=[('DISPOSITIVO', 'Dispositivo'), ('USB', 'USB'), ('EXCEL', 'Importacion Excel')], default='DISPOSITIVO', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('ejecutado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descargas', to='core.dispositivo')),
            ],
            options={
                'db_table': 'descargas_marcaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_empleado', models.CharField(max_length=30, unique=True)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres_completos', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='core.area')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personales', to='core.cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='core.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='core.empresa')),
            ],
            options={
                'db_table': 'personales',
                'ordering': ['nombres_completos'],
            },
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_equipo', models.CharField(blank=True, max_length=40)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], default='ENTRADA', max_length=10)),
                ('situacion', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('descarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcaciones', to='core.descargamarcacion')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcaciones', to='core.dispositivo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='core.personal')),
            ],
            options={
                'db_table': 'marcaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DescansoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(choices=[('SALUD', 'Por salud'), ('SUBSIDIO', 'Subsidio')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(default=1)),
                ('citt', models.CharField(blank=True, max_length=60)),
                ('diagnostico', models.CharField(blank=True, max_length=255)),
                ('tiene_adjunto', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(blank=True, max_length=60)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos_medicos', to='core.personal')),
            ],
            options={
                'db_table': 'descansos_medicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='boletamensual',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='core.personal'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa')),
            ],
            options={
                'db_table': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='core.sucursal'),
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('SALIDA', 'Salida'), ('INGRESO', 'Ingreso')], default='SALIDA', max_length=10)),
                ('rango', models.CharField(choices=[('PARCIAL', 'Parcial'), ('COMPLETO', 'Completo')], default='PARCIAL', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('tiene_adjunto', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('nombre_documento', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('AUTORIZADO', 'Autorizado'), ('NO_AUTORIZADO', 'No Autorizado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('fecha_gestion', models.DateTimeField(blank=True, null=True)),
                ('motivo_no_autorizacion', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones', to='core.area')),
                ('gestionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='core.personal')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones', to='core.sucursal')),
            ],
            options={
                'db_table': 'justificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='core.tipodocumento'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_sindicato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='core.tiposindicato'),
        ),
        migrations.AddField(
            model_name='personal',
            name='tipo_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='core.tipotrabajador'),
        ),
        migrations.CreateModel(
            name='PersonalTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='core.personal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_personal', to='core.turno')),
            ],
            options={
                'db_table': 'personal_turnos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TurnoBloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='core.turno')),
            ],
            options={
                'db_table': 'turno_bloques_horario',
                'ordering': ['turno', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pais', models.CharField(default='Peru', max_length=80)),
                ('departamento', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('distrito', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'ubicaciones_geograficas',
                'ordering': ['departamento', 'provincia', 'distrito'],
                'constraints': [models.UniqueConstraint(fields=('pais', 'departamento', 'provincia', 'distrito'), name='uq_ubicacion_geo')],
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personales', to='core.ubicaciongeografica'),
        ),
        migrations.CreateModel(
            name='LicenciaAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=180)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('AGUA', 'Activa'), ('TRANSFERIDA', 'Transferida'), ('ELIMINADA', 'Eliminada')], default='AGUA', max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='core.usuarioagua')),
            ],
            options={
                'db_table': 'licencias_agua',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='boletamensual',
            constraint=models.UniqueConstraint(fields=('personal', 'anio', 'mes'), name='uq_boleta_personal_periodo'),
        ),
        migrations.AddConstraint(
            model_name='boletamensual',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='ck_boleta_mes_1_12'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_sucursal_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_area_sucursal_codigo'),
        ),
        migrations.AddConstraint(
            model_name='turnobloquehorario',
            constraint=models.UniqueConstraint(fields=('turno', 'orden'), name='uq_turno_bloque_orden'),
        ),
        migrations.AddConstraint(
            model_name='licenciaagua',
            constraint=models.UniqueConstraint(fields=('usuario', 'numero'), name='uq_licencia_agua_usuario_numero'),
        ),
    ]
