# Generated by Django 6.0.2 on 2026-02-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("GERENCIA", "Gerencia"),
                    ("OFICINA", "Oficina"),
                    ("SUBGERENCIA", "Subgerencia"),
                    ("UNIDAD", "Unidad"),
                ],
                default="GERENCIA",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.area",
            ),
        ),
    ]
