# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporte_personal_mensual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteIncidenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('TARDANZA', 'Tardanza'), ('FALTA', 'Falta'), ('JUSTIFICACION', 'Justificacion'), ('DESCANSO_MEDICO', 'Descanso medico'), ('LICENCIA', 'Licencia'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_dias', models.PositiveSmallIntegerField(default=0)),
                ('cantidad_minutos', models.PositiveIntegerField(default=0)),
                ('referencia_modelo', models.CharField(blank=True, max_length=50)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='reporte_personal_mensual.reportepersonalmensual')),
            ],
            options={
                'db_table': 'reportes_incidencias_personal',
                'ordering': ['reporte', 'fecha_inicio', 'tipo'],
            },
        ),
    ]
