# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descarga_marcacion', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_equipo', models.CharField(blank=True, max_length=40)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_evento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], default='ENTRADA', max_length=10)),
                ('situacion', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('descarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcaciones', to='descarga_marcacion.descargamarcacion')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcaciones', to='personal.dispositivo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='personal.personal')),
            ],
            options={
                'db_table': 'marcaciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
