# Generated by Django 6.0.2 on 2026-04-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descarga_marcacion', '0001_initial'),
        ('marcacion', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['fecha_hora'], name='idx_marcacion_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['personal', 'fecha_hora'], name='idx_marcacion_personal_fecha'),
        ),
        migrations.AddIndex(
            model_name='marcacion',
            index=models.Index(fields=['situacion'], name='idx_marcacion_situacion'),
        ),
    ]
