# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('GENERAL_PERSONALIZADO', 'General Personalizado'), ('DESCANSO', 'Descanso')], default='GENERAL', max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='personal.personal')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_personal', to='turnos.turno')),
            ],
            options={
                'db_table': 'personal_turnos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TurnoBloqueHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='turnos.turno')),
            ],
            options={
                'db_table': 'turno_bloques_horario',
                'ordering': ['turno', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('turno', 'orden'), name='uq_turno_bloque_orden')],
            },
        ),
    ]
