# Generated by Django 6.0.2 on 2026-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="personalturno",
            index=models.Index(
                fields=["personal", "fecha_inicio", "fecha_fin"],
                name="idx_personal_turno_rango",
            ),
        ),
        migrations.AddIndex(
            model_name="personalturno",
            index=models.Index(fields=["turno"], name="idx_personal_turno_turno"),
        ),
    ]
