# Generated by Django 6.0.2 on 2026-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turnos", "0002_personal_turno_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="turno",
            index=models.Index(fields=["nombre"], name="idx_turno_nombre"),
        ),
        migrations.AddIndex(
            model_name="turno",
            index=models.Index(fields=["activo", "tipo", "nombre"], name="idx_turno_activo_tipo_nom"),
        ),
    ]
