# Generated by Django 6.0.2 on 2026-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tipo_trabajador", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tipotrabajador",
            index=models.Index(fields=["descripcion"], name="idx_tipo_trab_desc"),
        ),
        migrations.AddIndex(
            model_name="tipotrabajador",
            index=models.Index(fields=["activo", "descripcion"], name="idx_tipo_trab_activo_desc"),
        ),
    ]
