# Generated by Django 6.0.2 on 2026-04-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sucursal", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sucursal",
            index=models.Index(fields=["nombre"], name="idx_sucursal_nombre"),
        ),
        migrations.AddIndex(
            model_name="sucursal",
            index=models.Index(fields=["empresa", "nombre"], name="idx_sucursal_empresa_nombre"),
        ),
        migrations.AddIndex(
            model_name="sucursal",
            index=models.Index(fields=["activo", "nombre"], name="idx_sucursal_activo_nombre"),
        ),
    ]
