# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('personal', '0001_initial'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('SALIDA', 'Salida'), ('INGRESO', 'Ingreso')], default='SALIDA', max_length=10)),
                ('rango', models.CharField(choices=[('PARCIAL', 'Parcial'), ('COMPLETO', 'Completo')], default='PARCIAL', max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
                ('tiene_adjunto', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('nombre_documento', models.CharField(blank=True, max_length=180)),
                ('estado', models.CharField(choices=[('AUTORIZADO', 'Autorizado'), ('NO_AUTORIZADO', 'No Autorizado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('fecha_gestion', models.DateTimeField(blank=True, null=True)),
                ('motivo_no_autorizacion', models.TextField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones', to='area.area')),
                ('gestionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='personal.personal')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones', to='sucursal.sucursal')),
            ],
            options={
                'db_table': 'justificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
