# Generated by Django 6.0.2 on 2026-04-15 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('justificacion', '0001_initial'),
        ('personal', '0001_initial'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['estado'], name='idx_justificacion_estado'),
        ),
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['fecha_inicio'], name='idx_justificacion_fecha_ini'),
        ),
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['fecha_fin'], name='idx_justificacion_fecha_fin'),
        ),
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['estado', 'fecha_inicio', 'fecha_fin'], name='idx_justif_estado_rango'),
        ),
        migrations.AddIndex(
            model_name='justificacion',
            index=models.Index(fields=['personal', 'fecha_inicio', 'fecha_fin'], name='idx_justif_personal_rango'),
        ),
    ]
