# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporte_personal_mensual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteConceptoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('DESCUENTO', 'Descuento'), ('APORTE_TRABAJADOR', 'Aporte trabajador'), ('APORTE_EMPLEADOR', 'Aporte empleador'), ('OTRO', 'Otro')], default='INGRESO', max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('concepto', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_reporte', to='reporte_personal_mensual.reportepersonalmensual')),
            ],
            options={
                'db_table': 'reportes_conceptos_personal',
                'ordering': ['reporte', 'orden', 'tipo', 'concepto'],
            },
        ),
    ]
