# Generated by Django 6.0.2 on 2026-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tipo_sindicato", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tiposindicato",
            index=models.Index(fields=["descripcion"], name="idx_tipo_sind_desc"),
        ),
        migrations.AddIndex(
            model_name="tiposindicato",
            index=models.Index(fields=["activo", "descripcion"], name="idx_tipo_sind_activo_desc"),
        ),
    ]
