# Generated by Django 6.0.2 on 2026-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cargo", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["descripcion"], name="idx_cargo_descripcion"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["activo", "descripcion"], name="idx_cargo_activo_desc"),
        ),
    ]
