# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
        ('cargo', '0001_initial'),
        ('categoria', '0001_initial'),
        ('empresa', '0001_initial'),
        ('sucursal', '0001_initial'),
        ('tipo_documento', '0001_initial'),
        ('tipo_sindicato', '0001_initial'),
        ('tipo_trabajador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('direccion_tipo', models.CharField(choices=[('IP', 'Direccion IP'), ('DOMINIO', 'Dominio')], default='IP', max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('comunicacion', models.CharField(default='TCP/IP', max_length=40)),
                ('puerto', models.PositiveIntegerField(default=4370)),
                ('uso', models.CharField(choices=[('ASISTENCIA', 'Control de Asistencia'), ('ACCESO', 'Control de Acceso')], default='ASISTENCIA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dispositivos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pais', models.CharField(default='Peru', max_length=80)),
                ('departamento', models.CharField(max_length=80)),
                ('provincia', models.CharField(max_length=80)),
                ('distrito', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'ubicaciones_geograficas',
                'ordering': ['departamento', 'provincia', 'distrito'],
                'constraints': [models.UniqueConstraint(fields=('pais', 'departamento', 'provincia', 'distrito'), name='uq_ubicacion_geo')],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo_empleado', models.CharField(max_length=30, unique=True)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres_completos', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='area.area')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personales', to='cargo.cargo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='categoria.categoria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='empresa.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='sucursal.sucursal')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='tipo_documento.tipodocumento')),
                ('tipo_sindicato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='tipo_sindicato.tiposindicato')),
                ('tipo_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personales', to='tipo_trabajador.tipotrabajador')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personales', to='personal.ubicaciongeografica')),
            ],
            options={
                'db_table': 'personales',
                'ordering': ['nombres_completos'],
            },
        ),
    ]
