# Generated by Django 6.0.2 on 2026-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dispositivo",
            index=models.Index(fields=["nombre"], name="idx_dispositivo_nombre"),
        ),
        migrations.AddIndex(
            model_name="dispositivo",
            index=models.Index(fields=["activo", "uso", "nombre"], name="idx_disp_activo_uso_nom"),
        ),
    ]
