# Generated by Django 6.0.2 on 2026-04-21 00:00

from django.db import migrations, models


def copy_ubicacion_to_texto(apps, schema_editor):
    Personal = apps.get_model("personal", "Personal")

    for personal in Personal.objects.select_related("ubicacion").all().iterator():
        if not getattr(personal, "ubicacion_id", None):
            continue
        ubicacion = personal.ubicacion
        if ubicacion is None:
            continue
        departamento = (getattr(ubicacion, "departamento", "") or "").strip()
        provincia = (getattr(ubicacion, "provincia", "") or "").strip()
        distrito = (getattr(ubicacion, "distrito", "") or "").strip()
        label = " / ".join([x for x in (departamento, provincia, distrito) if x])
        personal.ubicacion_texto = label
        personal.save(update_fields=["ubicacion_texto"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_dispositivo_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="ubicacion_texto",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RunPython(copy_ubicacion_to_texto, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name="personal",
            name="ubicacion",
        ),
        migrations.RenameField(
            model_name="personal",
            old_name="ubicacion_texto",
            new_name="ubicacion",
        ),
    ]

