# Generated by Django 6.0.2 on 2026-04-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0003_personal_ubicacion_texto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personal",
            old_name="ubicacion",
            new_name="direccion",
        ),
    ]

