# Generated by Django 6.0.2 on 2026-04-21 00:00

from django.db import migrations, models


def copy_tipo_documento_to_texto(apps, schema_editor):
    Personal = apps.get_model("personal", "Personal")

    for personal in Personal.objects.select_related("tipo_documento").all().iterator():
        tipo = "DNI"
        td = getattr(personal, "tipo_documento", None)
        if td is not None:
            raw = (
                (getattr(td, "codigo", "") or "").strip()
                or (getattr(td, "descripcion", "") or "").strip()
                or str(td).strip()
            )
            raw_upper = raw.upper()
            if "DNI" in raw_upper:
                tipo = "DNI"
            elif "CARNET" in raw_upper or "CARNÉ" in raw_upper:
                tipo = "CARNET"
            elif raw_upper:
                tipo = raw_upper[:20]
        personal.tipo_documento_texto = tipo
        personal.save(update_fields=["tipo_documento_texto"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0004_personal_renombrar_ubicacion_a_direccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="tipo_documento_texto",
            field=models.CharField(default="DNI", max_length=20),
        ),
        migrations.RunPython(copy_tipo_documento_to_texto, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name="personal",
            name="tipo_documento",
        ),
        migrations.RenameField(
            model_name="personal",
            old_name="tipo_documento_texto",
            new_name="tipo_documento",
        ),
    ]

