# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('GERENCIA', 'Gerencia'), ('OFICINA', 'Oficina'), ('SUBGERENCIA', 'Subgerencia'), ('UNIDAD', 'Unidad')], default='GERENCIA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='area.area')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='sucursal.sucursal')),
            ],
            options={
                'db_table': 'areas',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('sucursal', 'codigo'), name='uq_area_sucursal_codigo')],
            },
        ),
    ]
