# Generated by Django 6.0.2 on 2026-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("area", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["nombre"], name="idx_area_nombre"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["sucursal", "nombre"], name="idx_area_sucursal_nombre"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["activo", "nombre"], name="idx_area_activo_nombre"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["tipo", "sucursal"], name="idx_area_tipo_sucursal"),
        ),
    ]
