# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescansoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(choices=[('SALUD', 'Por salud'), ('SUBSIDIO', 'Subsidio')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.PositiveIntegerField(default=1)),
                ('citt', models.CharField(blank=True, max_length=60)),
                ('diagnostico', models.CharField(blank=True, max_length=255)),
                ('tiene_adjunto', models.BooleanField(default=False)),
                ('numero_documento', models.CharField(blank=True, max_length=60)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos_medicos', to='personal.personal')),
            ],
            options={
                'db_table': 'descansos_medicos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
