# Generated by Django 6.0.2 on 2026-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descanso_medico", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="descansomedico",
            index=models.Index(fields=["fecha_inicio"], name="idx_descanso_fecha_ini"),
        ),
        migrations.AddIndex(
            model_name="descansomedico",
            index=models.Index(fields=["fecha_fin"], name="idx_descanso_fecha_fin"),
        ),
        migrations.AddIndex(
            model_name="descansomedico",
            index=models.Index(
                fields=["personal", "fecha_inicio", "fecha_fin"],
                name="idx_descanso_personal_rango",
            ),
        ),
    ]
