# Generated by Django 6.0.2 on 2026-04-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('sueldo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('GENERADA', 'Generada'), ('DESCARGADA', 'Descargada'), ('ANULADA', 'Anulada')], default='GENERADA', max_length=12)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas', to='personal.personal')),
            ],
            options={
                'db_table': 'boletas_mensuales',
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('personal', 'anio', 'mes'), name='uq_boleta_personal_periodo'), models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='ck_boleta_mes_1_12')],
            },
        ),
    ]
