# Generated by Django 6.0.2 on 2026-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="categoria",
            index=models.Index(fields=["descripcion"], name="idx_categoria_desc"),
        ),
        migrations.AddIndex(
            model_name="categoria",
            index=models.Index(fields=["activo", "descripcion"], name="idx_categoria_activo_desc"),
        ),
    ]
