# Generated by Django 6.0.2 on 2026-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('logo', models.FileField(blank=True, null=True, upload_to='empresas/logos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
    ]
