# Generated by Django 6.0.2 on 2026-04-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["razon_social"], name="idx_empresa_razon_social"),
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["activo", "razon_social"], name="idx_empresa_activo_razon"),
        ),
    ]
